"""Generate the checked-in public notebook deterministically."""
from __future__ import annotations

import json
from pathlib import Path

try:
    from .notebook_validation import validate_code_source
except ImportError:
    from notebook_validation import validate_code_source

ROOT = Path(__file__).resolve().parents[1]


def code(source: str) -> dict:
    validate_code_source(source, "generated:Diarizator_Community1_Colab.ipynb", "pending")
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": source.splitlines(keepends=True)}


def markdown(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source.splitlines(keepends=True)}


cells = [
    markdown("""# Diarizator Community-1 — upload-first Colab\n\n**Standard workflow:** add `HF_TOKEN` to Colab Secrets, select **Run all**, upload one supported file, and download the sanitized ZIP. Google Drive is not required. Select a GPU runtime first.\n\nCommunity-1 is gated: accept the conditions on the [official model page](https://huggingface.co/pyannote/speaker-diarization-community-1), create a read token, add it as the `HF_TOKEN` secret, and enable notebook access. Never paste a token into a cell.\n"""),
    code("""# Validated dependency profile and safe two-pass restart guard.\nimport importlib.metadata as md, json, subprocess, sys, urllib.request\nOWNER = "Favioleiva"\nREPOSITORY = "diarizator"\nREF = "main"  # Replace with v0.1.0 only after the release is validated.\nREPO_URL = f"https://github.com/{OWNER}/{REPOSITORY}.git"\nRAW = f"https://raw.githubusercontent.com/{OWNER}/{REPOSITORY}/{REF}/colab"\nEXPECTED = {"numpy":"2.2.2", "scipy":"1.16.3", "pandas":"2.2.3", "jedi":"0.19.2", "faster-whisper":"1.2.1", "pyannote.audio":"4.0.7", "pyannote.metrics":"4.1", "opentelemetry-api":"1.42.1", "opentelemetry-sdk":"1.42.1"}\nrequirements = "/content/requirements-colab.txt"\nconstraints = "/content/constraints-colab.txt"\nfor url, target in ((RAW + "/requirements-colab.txt", requirements), (RAW + "/constraints-colab.txt", constraints)):\n    urllib.request.urlretrieve(url, target)\ncurrent = {}\nfor package in EXPECTED:\n    try: current[package] = md.version(package)\n    except md.PackageNotFoundError: current[package] = None\nbinary_probe = subprocess.run([sys.executable, "-c", "import numpy, scipy; print(numpy.__version__, scipy.__version__)"], capture_output=True, text=True)\nneeds_install = current != EXPECTED or binary_probe.returncode != 0\nif needs_install:\n    subprocess.check_call([sys.executable, "-m", "pip", "install", "--upgrade", "--force-reinstall", "numpy==2.2.2", "scipy==1.16.3"])\n    subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", requirements, "-c", constraints])\n    subprocess.check_call([sys.executable, "-m", "pip", "install", "--no-deps", f"diarizator @ git+{REPO_URL}@{REF}"])\n    probe = subprocess.run([sys.executable, "-c", "import numpy, scipy, pandas, diarizator; print('BINARY_IMPORTS_OK')"], capture_output=True, text=True)\n    if probe.returncode: raise RuntimeError(probe.stderr[-2000:])\n    print("Dependencies installed and verified in a fresh process. Choose Runtime > Restart session, then Run all again.")\n    raise SystemExit("DEPENDENCIES_INSTALLED_RESTART_REQUIRED")\nsubprocess.check_call([sys.executable, "-m", "pip", "install", "--no-deps", f"diarizator @ git+{REPO_URL}@{REF}"])\ncheck = subprocess.run([sys.executable, "-m", "pip", "check"], capture_output=True, text=True)\nknown = ("google-colab 1.0.0 has requirement pandas==2.2.2", "numba 0.60.0 has requirement numpy<2.1,>=1.22")\nunexpected = [line for line in check.stdout.splitlines() if line and not any(item in line for item in known)]\nif unexpected: raise RuntimeError("Unexpected dependency conflicts: " + json.dumps(unexpected))\nprint("DEPENDENCY_PROFILE_OK")\n"""),
    markdown("""## Optional configuration\n\nThe default is **Upload my own audio** with automatic speaker-count estimation. Advanced users may choose exact or bounded counts. The bundled demonstration may use its known exact two-character structure; arbitrary uploads never silently use that setting.\n"""),
    code("""INPUT_CHOICE = "Upload my own audio"  # or: Use bundled demonstration audio\nSPEAKER_COUNT_MODE = "estimated"  # estimated, exact, or bounded\nNUM_SPEAKERS = None\nMIN_SPEAKERS = None\nMAX_SPEAKERS = None\nDEMO_SPEAKER_COUNT_MODE = "exact"  # exact or estimated\nif SPEAKER_COUNT_MODE not in {"estimated", "exact", "bounded"}: raise ValueError("Invalid speaker-count mode")\nif SPEAKER_COUNT_MODE == "exact" and (not isinstance(NUM_SPEAKERS, int) or NUM_SPEAKERS < 1): raise ValueError("Exact mode requires NUM_SPEAKERS >= 1")\nif SPEAKER_COUNT_MODE == "bounded" and (not isinstance(MIN_SPEAKERS, int) or not isinstance(MAX_SPEAKERS, int) or MIN_SPEAKERS < 1 or MAX_SPEAKERS <= MIN_SPEAKERS): raise ValueError("Bounded mode requires 1 <= MIN_SPEAKERS < MAX_SPEAKERS")\n"""),
    code("""# Secure authentication and Community-1 access preflight happen before ASR.\nfrom google.colab import userdata\nfrom diarizator.access import preflight_model_access\nHF_TOKEN = userdata.get("HF_TOKEN")\naccess = preflight_model_access(token=HF_TOKEN)\nprint("Community-1 access:", access["status"])\nif access["status"] not in {"MODEL_CACHED", "MODEL_ACCESS_CONFIRMED"}:\n    raise RuntimeError("Community-1 preflight stopped safely: " + access["status"])\n"""),
    markdown("""## Select one input\n\nSupported formats include MP3, M4A/AAC, WAV, FLAC, OGG/OPUS, and audio tracks from common MP4, MOV, MKV, and WebM files. For faster browser uploads, a compressed format such as MP3 is recommended. M4A/AAC is also compact. WAV files are usually much larger. This is about upload size—not accuracy.\n"""),
    code("""from pathlib import Path\nimport shutil, subprocess, sys, tempfile\nfrom google.colab import files\nworkspace = Path(tempfile.mkdtemp(prefix="diarizator-"))\nif INPUT_CHOICE == "Upload my own audio":\n    uploaded = files.upload()\n    if len(uploaded) != 1: raise ValueError("Upload exactly one supported audio or video file.")\n    filename, payload = next(iter(uploaded.items()))\n    audio_path = workspace / Path(filename).name\n    audio_path.write_bytes(payload)\n    mode, number, lower, upper = SPEAKER_COUNT_MODE, NUM_SPEAKERS, MIN_SPEAKERS, MAX_SPEAKERS\nelif INPUT_CHOICE == "Use bundled demonstration audio":\n    source = "https://raw.githubusercontent.com/Favioleiva/diarizator/main/examples/controlled_demo/The_Measure_of_a_Good_Life.mp3"\n    audio_path = workspace / "The_Measure_of_a_Good_Life.mp3"\n    urllib.request.urlretrieve(source, audio_path)\n    mode = DEMO_SPEAKER_COUNT_MODE\n    number, lower, upper = (2 if mode == "exact" else None), None, None\nelse: raise ValueError("Unknown input choice")\nfrom diarizator.media import inspect_media\nprint(json.dumps(inspect_media(audio_path), indent=2))\n"""),
    code("""from diarizator import diarize\nfrom diarizator.bundle import create_bundle\nresult_dir = diarize(audio_path, workspace / "results", token=HF_TOKEN, speaker_count_mode=mode, num_speakers=number, min_speakers=lower, max_speakers=upper)\nbundle_path = workspace / "diarizator-results.zip"\nbundle = create_bundle([result_dir], bundle_path)\nrun = json.loads((result_dir / "run.json").read_text())\nenvironment = json.loads((result_dir / "environment.json").read_text())\ndiarization = json.loads((result_dir / "diarization.json").read_text())\nprint(json.dumps({"zip_filename": bundle_path.name, "zip_path": str(bundle_path), "zip_size_bytes": bundle_path.stat().st_size, "zip_sha256": bundle["sha256"], "detected_gpu": environment["device"], "backend": run["config"]["diarization"]["backend"], "speaker_count_mode": run["speaker_count_mode"], "detected_speaker_count": diarization["estimated_speakers"], "run_status": run["status"]}, indent=2))\nfiles.download(str(bundle_path))\n"""),
]

notebook = {
    "cells": cells,
    "metadata": {"accelerator": "GPU", "colab": {"name": "Diarizator_Community1_Colab.ipynb", "provenance": []}, "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}, "language_info": {"name": "python"}},
    "nbformat": 4,
    "nbformat_minor": 5,
}
(ROOT / "notebooks" / "Diarizator_Community1_Colab.ipynb").write_text(json.dumps(notebook, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
